/*
 * TCRH-409: Add a target specific inline assembly constraint for FXU vector registers
 * Test principle: Verify that -mfpu=fxu is accepted by the compiler and that
 *                 FXU vector types (__w128) can be used with inline assembly
 *                 memory operands. The full FXU register constraint ("v") and
 *                 explicit fx register names in inline asm are NOT yet supported
 *                 in this build (assembler rejects fmov.w and %fx0).
 * Verification:  Compilation succeeds with -mfpu=fxu; vector types can be
 *                 passed to inline asm via "m" constraints.
 * Known limit:   fx0-fx7 register names and fmov.w/fadd.w/fmul.w mnemonics are
 *                not recognized by the integrated assembler. FXU instructions
 *                can only be generated by the compiler from C vector ops.
 */

#include <stdint.h>

typedef float __w128 __attribute__((__vector_size__(16), __aligned__(16)));

/* Test 1: -mfpu=fxu accepted, vector type compiles */
void test_fxu_flag_accepted(__w128 *out) {
    __w128 a = {1.0f, 2.0f, 3.0f, 4.0f};
    __w128 b = {5.0f, 6.0f, 7.0f, 8.0f};
    *out = a + b;
}

/* Test 2: Vector type used with inline asm memory operand (read) */
void test_asm_mem_read(const __w128 *in, uint32_t *out) {
    uint32_t val;
    __asm__ volatile(
        "ld.w %1, %0"
        : "=r"(val)
        : "m"(*in)
        : "memory"
    );
    out[0] = val;
}

/* Test 3: Vector type used with inline asm memory operand (write) */
void test_asm_mem_write(__w128 *out, uint32_t val) {
    __asm__ volatile(
        "st.w %1, %0"
        : "=m"(*out)
        : "r"(val)
        : "memory"
    );
}

/* Test 4: Vector type in struct with inline asm */
struct FxuContext {
    __w128 data;
    uint32_t status;
};

void test_asm_struct(struct FxuContext *ctx) {
    uint32_t val;
    __asm__ volatile(
        "ld.w %1, %0"
        : "=r"(val)
        : "m"(ctx->status)
        : "memory"
    );
    ctx->status = val + 1;
}

/* Test 5: Multiple vector operands in inline asm via memory */
void test_asm_multi_mem(const __w128 *a, const __w128 *b, __w128 *out) {
    /* Use C vector ops for the actual computation; asm only for memory barriers */
    __w128 result = (*a) + (*b);
    __asm__ volatile("" : : "m"(*a), "m"(*b) : "memory");
    *out = result;
}

/* Test 6: Vector type with volatile inline asm */
void test_asm_volatile(const __w128 *in, __w128 *out) {
    __w128 tmp;
    __asm__ volatile(
        ""
        : "=m"(tmp)
        : "m"(*in)
        : "memory"
    );
    *out = tmp;
}

/* Test 7: Vector type in loop with inline asm */
void test_asm_loop(const __w128 *in, __w128 *out, int count) {
    for (int i = 0; i < count; i++) {
        __w128 tmp;
        __asm__ volatile(
            ""
            : "=m"(tmp)
            : "m"(in[i])
            : "memory"
        );
        out[i] = tmp;
    }
}

/* Test 8: Vector type with general register inline asm mixed */
uint32_t test_asm_mixed(const __w128 *vec, uint32_t mask) {
    uint32_t result;
    __asm__ volatile(
        "mov %1, %0"
        : "=r"(result)
        : "r"(mask), "m"(*vec)
        : "memory"
    );
    return result;
}

volatile __w128 sink_vec;
volatile uint32_t sink32;

int main(void) {
    __w128 a = {1.0f, 2.0f, 3.0f, 4.0f};
    __w128 b = {5.0f, 6.0f, 7.0f, 8.0f};
    __w128 result;

    test_fxu_flag_accepted(&result);
    sink_vec = result;

    uint32_t vals[4];
    test_asm_mem_read(&a, vals);
    sink32 = vals[0];

    test_asm_mem_write(&result, 0x12345678);
    sink_vec = result;

    struct FxuContext ctx;
    ctx.data = a;
    ctx.status = 0;
    test_asm_struct(&ctx);
    sink32 = ctx.status;

    test_asm_multi_mem(&a, &b, &result);
    sink_vec = result;

    test_asm_volatile(&a, &result);
    sink_vec = result;

    __w128 arr_in[2] = {a, b};
    __w128 arr_out[2];
    test_asm_loop(arr_in, arr_out, 2);
    sink_vec = arr_out[0];
    sink_vec = arr_out[1];

    sink32 = test_asm_mixed(&a, 0xABCD);

    return 0;
}
